version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:${MINIO_PORT}"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio-data:/data  
    networks:
      - app-network
    command: server /data --console-address ":9001"
    restart: always
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--jetstream"]
    restart: always
  postgres:
    image: postgres:14.0
    shm_size: 1g
    container_name: psql-db
    command: postgres -c 'max_connections=500'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE_NAME}
    ports:
      - "5432:${PG_PORT}"
    networks:
      - app-network
  migrator:
    build:
      context: .
      dockerfile: docker/migrator.Dockerfile
    restart: on-failure
    environment:
       DB_HOST: postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data:



